name: Repository Variable Demo
on: 
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo "Hello, ${{ vars.AUTOBOTS_LEADER }}"
  
